version: "3.9"

services:
  storefront: 
    build:
      context: .
      args:
      - region=us-east-1
        - pranav=true
    environment:
      - runtime_user=pranav
  database: 
    image: "mysql"
